#!/bin/bash 
PRETRAINED_MODEL_PATH="stabilityai/stable-diffusion-xl-base-1.0"
INSTANCE_DATA_DIR="example/style"
OUTPUT_DIR="lora/style"
# content enchance prompt (generated by llm such as gpt4o or manually)
INSTANCE_PROMPT="A man with long black hair wears a black jacket over a white shirt in <s> style."
RESOLUTION=512
RANK=64
TRAIN_BATCH_SIZE=1
LEARNING_RATE=1e-5
LR_SCHEDULER="constant"
LR_WARMUP_STEPS=50
MAX_TRAIN_STEPS=1000
CHECKPOINTING_STEPS=1000

python3 -m accelerate.commands.launch train_style_disentanglement.py \
    --pretrained_model_name_or_path="$PRETRAINED_MODEL_PATH" \
    --instance_data_dir="$INSTANCE_DATA_DIR" \
    --output_dir="$OUTPUT_DIR" \
    --instance_prompt="$INSTANCE_PROMPT" \
    --resolution="$RESOLUTION" \
    --rank="$RANK" \
    --train_batch_size="$TRAIN_BATCH_SIZE" \
    --learning_rate="$LEARNING_RATE" \
    --lr_scheduler="$LR_SCHEDULER" \
    --lr_warmup_steps="$LR_WARMUP_STEPS" \
    --max_train_steps="$MAX_TRAIN_STEPS" \
    --checkpointing_steps="$CHECKPOINTING_STEPS" \
    --seed="0" \
    --gradient_checkpointing \
    --use_8bit_adam \
    --mixed_precision=fp16